# Generated by Django 5.0.4 on 2024-05-14 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('user', '0003_remove_student_user_remove_teacher_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField(blank=True, max_length=300, null=True)),
                ('start_time', models.TimeField(max_length=200, null=True)),
                ('end_time', models.TimeField(max_length=200, null=True)),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.customuser')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
