# Generated by Django 5.0.4 on 2024-05-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_schedule_day_remove_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
