# Generated by Django 5.0.4 on 2024-06-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_description_schedule_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='link',
            new_name='url',
        ),
    ]
