# Generated by Django 5.0.4 on 2024-06-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_rename_link_schedule_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(default='title', max_length=255),
        ),
    ]
