# Generated by Django 5.0.4 on 2024-06-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_schedule_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='title',
        ),
    ]
