# Generated by Django 5.0.6 on 2024-05-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='term',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='tittle',
        ),
    ]
