# Generated by Django 5.0.4 on 2024-05-25 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_rename_term_subject_title_remove_subject_tittle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'is_student': True}, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
