# Generated by Django 5.0.4 on 2024-06-14 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_material_materialfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_student': True}, null=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
